### ISSUE TITLE
keine Tabs zusehen (Contao 3.2.7)

### ISSUE THREAD

**Issue by srhinow** [slashworks/contao-themeTabs#1]
Hallo,
nach der Installation der themeTabs-Erweiterung in eine ziemlich frische Neuinstallation von Contao 3.2.7 kann ich keinen Unterschied unter Themes feststellen. In allen Unterbereichen wie CSS, Module und Templates sieht es genauso aus wie vor der Modulinstallation.

**Comment by may17** [comment]
Das ist sehr merkwürdig. Habe das Modul gerade neu installiert und es funktioniert so wie es soll in einer frischen 3.2.7. 

Hast du das Modul über das ER im Backend installiert?
Hast du noch weitere Module installiert?

**Comment by srhinow** [comment]
ja ich hab das Modul über ER aus dem Backend raus installiert. Weiterhin
installiert hab ich folgende Module
backupDB
tags
tags_news

**Comment by srhinow** [comment]
hat sich erledigt. beim letzten System-Update hats wohl fastcgi zerledert. Habs jetzt gefixt und die Erweiterung themeTabs deinstalliert und wieder neu installiert. Jetzt seh ich auch alles wie es sein soll. Hat dann wohl an irgendwelchen fehlenden Schreib-Rechten bei der Installation gelegen.

Danke für die Erweiterung :)
